name: Kira
version: 1.0
author: birajrai
load: STARTUP
main: me.birajrai.Kira
api-version: 1.8.8
commands:
  #[] optional
  #<> required
  heal:
    description: Heal a player
  feed:
    description: Feed a player
  vanish:
    description: Vanish
  report:
    description: Report a player
  staff:
    description: Equip staff tools
  chat:
    description: Switch chat regions